FROM node:22-alpine

WORKDIR /app

COPY libs ./libs

WORKDIR /app/services/auth

COPY services/auth/package*.json ./
COPY services/auth/tsconfig.json ./
COPY services/auth/prisma ./prisma

RUN npm install
RUN npx prisma generate

COPY services/auth/src ./src
COPY services/auth/. .

CMD ["npm", "run", "go"]