FROM node:22-alpine

WORKDIR /app/services/metrics

COPY services/metrics/package*.json ./
COPY services/metrics/tsconfig.json ./
COPY services/metrics/prisma ./prisma

RUN npm install
RUN npx prisma generate

COPY services/metrics/src ./src
COPY services/metrics/. .

CMD ["npm", "run", "go"]