FROM node:22-alpine

WORKDIR /app/services/invite

COPY services/invite/package*.json ./
COPY services/invite/tsconfig.json ./
COPY services/invite/prisma ./prisma

RUN npm install
RUN npx prisma generate

COPY services/invite/src ./src
COPY services/invite/. .

CMD ["npm", "run", "go"]