FROM node:22-alpine

WORKDIR /app/services/audit

COPY services/audit/package*.json ./
COPY services/audit/tsconfig.json ./
COPY services/audit/prisma ./prisma

RUN npm install
RUN npx prisma generate

COPY services/audit/src ./src
COPY services/audit/. .

CMD ["npm", "run", "go"]