FROM node:22-alpine

WORKDIR /app

COPY libs ./libs

WORKDIR /app/services/org

COPY services/org/package*.json ./
COPY services/org/tsconfig.json ./
COPY services/org/prisma ./prisma

RUN npm install
RUN npx prisma generate

COPY services/org/src ./src
COPY services/org/. .

CMD ["npm", "run", "go"]