FROM node:22-alpine

WORKDIR /app

COPY libs ./libs

WORKDIR /app/services/users

COPY services/users/package*.json ./
COPY services/users/tsconfig.json ./
COPY services/users/prisma ./prisma

RUN npm install
RUN npx prisma generate

COPY services/users/src ./src
COPY services/users/. .

CMD ["npm", "run", "go"]